# Generated by Django 5.1.7 on 2025-03-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('oz', 'Ounce (oz)'), ('tbsp', 'Tablespoon (tbsp)'), ('tsp', 'Teaspoon (tsp)'), ('cup', 'Cup'), ('ml', 'Milliliter (ml)'), ('cl', 'Centiliter (cl)'), ('liter', 'Liter'), ('pinch', 'Pinch'), ('dash', 'Dash'), ('slice', 'Slice'), ('whole', 'Whole'), ('drop', 'Drop'), ('none', 'None')], max_length=10)),
                ('garnish', models.BooleanField(default=False)),
                ('optional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('steps', models.JSONField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('Classic', 'Classic Cocktails'), ('Tropical', 'Tropical Cocktails'), ('Signature', 'Signature Cocktails'), ('Modern', 'Modern Cocktails'), ('Frozen', 'Frozen Cocktails'), ('Highball', 'Highball Cocktails'), ('Lowball', 'Lowball / Rocks Cocktails'), ('Sours', 'Sours'), ('Punch', 'Punch Cocktails'), ('Shots', 'Shots'), ('Martini', 'Martinis'), ('Champagne', 'Champagne & Sparkling Cocktails'), ('Mocktail', 'Mocktails')], max_length=20)),
                ('glass_type', models.CharField(choices=[('Bowl', 'Bowl'), ('Champagne Flute', 'Champagne Flute'), ('Cocktail Glass', 'Cocktail Glass'), ('Collins Glass', 'Collins Glass'), ('Copper mug', 'Copper mug'), ('Coupe', 'Coupe'), ('Cup', 'Cup'), ('Goblet', 'Goblet'), ('Highball Glass', 'Highball Glass'), ('Hurricane Glass', 'Hurricane Glass'), ('Irish Coffee Glass', 'Irish Coffee Glass'), ('Margarita Glass', 'Margarita Glass'), ('Nick and Nora', 'Nick and Nora'), ('Pitcher', 'Pitcher'), ('Pub Glass', 'Pub Glass'), ('Rocks Glass', 'Rocks Glass'), ('Shooter', 'Shooter'), ('Snifter', 'Snifter'), ('Tiki', 'Tiki'), ('Wine Glass', 'Wine Glass')], max_length=20)),
                ('alcoholic', models.BooleanField(default=True)),
                ('shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='cocktail_comments', to='main_app.comment')),
                ('ingredients', models.ManyToManyField(to='main_app.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('collections', models.JSONField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('createdCocktails', models.ManyToManyField(blank=True, related_name='creators', to='main_app.cocktail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shared', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('cocktails', models.ManyToManyField(related_name='collections', to='main_app.cocktail')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to='main_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cocktails', to='main_app.user'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_cocktails', to='main_app.user'),
        ),
    ]
