# Generated by Django 5.1.7 on 2025-03-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
