# Generated by Django 5.1.7 on 2025-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_image_cocktail_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='steps',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='steps',
            field=models.ManyToManyField(to='main_app.step'),
        ),
    ]
