# Generated by Django 5.1.7 on 2025-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_step_remove_cocktail_steps_cocktail_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='shared',
            field=models.BooleanField(default=True),
        ),
    ]
