# Generated by Django 5.1.7 on 2025-03-31 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cocktail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cocktail'),
        ),
    ]
